- name: Install prerequisites for apt over HTTPS
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

- name: Add k8s repo
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: deb
    uris: https://pkgs.k8s.io/core:/stable:/v1.34/deb/
    suites: '/'
    architectures: amd64
    signed_by: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
  notify:
    - Update package lists

